"""init articles tracking materials

Revision ID: b5fcb48ec461
Revises: 
Create Date: 2026-08-03 20:59:27.007503
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5fcb48ec461'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('folder_name', sa.String(length=200), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('titles', sa.JSON(), nullable=True),
    sa.Column('contents', sa.JSON(), nullable=True),
    sa.Column('image_sources', sa.JSON(), nullable=True),
    sa.Column('publish_schedule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_status', ['status'], unique=False)
        batch_op.create_index('ix_articles_title', ['title'], unique=False)
        batch_op.create_index('ix_articles_updated_at', ['updated_at'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stem', sa.String(length=255), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('article_id', sa.String(length=200), nullable=True),
    sa.Column('work', sa.String(length=100), nullable=True),
    sa.Column('episode', sa.String(length=20), nullable=True),
    sa.Column('scene', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('characters', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mtime', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('ix_materials_article_id', ['article_id'], unique=False)
        batch_op.create_index('ix_materials_source', ['source'], unique=False)
        batch_op.create_index('ix_materials_stem', ['stem'], unique=False)
        batch_op.create_index('ix_materials_work_episode', ['work', 'episode'], unique=False)

    op.create_table('tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('article_id', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('title_used', sa.String(length=300), nullable=True),
    sa.Column('impress', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('bookmarks', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'article_id', 'platform', name='uq_tracking_date_article_platform')
    )
    with op.batch_alter_table('tracking', schema=None) as batch_op:
        batch_op.create_index('ix_tracking_article_id', ['article_id'], unique=False)
        batch_op.create_index('ix_tracking_platform_date', ['platform', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking', schema=None) as batch_op:
        batch_op.drop_index('ix_tracking_platform_date')
        batch_op.drop_index('ix_tracking_article_id')

    op.drop_table('tracking')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index('ix_materials_work_episode')
        batch_op.drop_index('ix_materials_stem')
        batch_op.drop_index('ix_materials_source')
        batch_op.drop_index('ix_materials_article_id')

    op.drop_table('materials')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_updated_at')
        batch_op.drop_index('ix_articles_title')
        batch_op.drop_index('ix_articles_status')

    op.drop_table('articles')
    # ### end Alembic commands ###
