"""phase2 weekly_plan and tracking revenue

Revision ID: fa99cadad32b
Revises: b5fcb48ec461
Create Date: 2026-08-03 22:12:03.657242
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa99cadad32b'
down_revision: Union[str, None] = 'b5fcb48ec461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('article_id', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_plan', schema=None) as batch_op:
        batch_op.create_index('ix_weekly_plan_article_id', ['article_id'], unique=False)
        batch_op.create_index('ix_weekly_plan_week_start', ['week_start'], unique=False)

    # NOT NULL 新列必须带 server_default，否则已有行（旧库 121 条追踪）无法回填。
    # 语义：0 = 尚未登记收益，不等于「确认没有收益」。
    with op.batch_alter_table('tracking', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('revenue_cents', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking', schema=None) as batch_op:
        batch_op.drop_column('revenue_cents')

    with op.batch_alter_table('weekly_plan', schema=None) as batch_op:
        batch_op.drop_index('ix_weekly_plan_week_start')
        batch_op.drop_index('ix_weekly_plan_article_id')

    op.drop_table('weekly_plan')
    # ### end Alembic commands ###
